[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rppal = "0.22.1"
axum = "0.8.1"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
async-stream = "0.3.6"
futures = "0.3.31"
