[garage_door]
close_limit_pin = 23
open_limit_pin = 24
coupler_pin = 25
coupler_active_low = true
poll_interval_ms = 50
expected_shut_time_sec = 15
shut_time_buffer_sec = 3
coupler_active_intervals = 2
coupler_rest_intervals = 10
limit_cooldown_ms = 250
server_address = "0.0.0.0:3000"
api_key = "your_secure_api_key_here"